local f = io.open('WAG.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 WAG.sh')
os.execute('killall -9 tg')
os.execute('rm -rf WAG.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('WAG.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 WAG.sh')
os.execute('screen ./WAG.sh')
